blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('videoportal/', include(('videoportal.urls', 'videoportal'), namespace='videoportal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
   path('', views.home, name='home'),
   path('about/', views.about, name='about'),
   path('contact/', views.contact, name='contact'),
   path('search/', views.search, name='search'),
   path('signup/', views.handleSignup, name='handleSignup'),
   path('login/', views.handleLogin, name='handleLogin'),
   path('logout/', views.handleLogout, name='handleLogout'),
]

videoportal/urls.py
from django.urls import path

from videoportal.views import (VideoListView, VideoDetailView, VideoFileView)

urlpatterns = [
    path('', VideoListView.as_view(), name='video-home'),
    path('video/<int:id>/', VideoDetailView.as_view(), name='video-detail'),
    path('get_video/<file_name>/', VideoFileView.as_view(), name='video-view'),
]

home/models.py
from django.db import models


# Create your models here.
# Database ----> Excel workbook
# Models In Django ----> Table  --------> Sheet

class Contact(models.Model):
    sno = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=13)
    email = models.CharField(max_length=100)
    content = models.TextField()
    timeStamp = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return 'Message from ' + self.name + ' - ' + self.email

home/views.py
from django.shortcuts import render, HttpResponse, redirect
from home.models import Contact
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from blog.models import Post
from videoportal.models import Video


def home(request):
    context = {
        'recent_post': Post.objects.all()[0],
        # 'recent_post': Post.objects.order_by('bakery__id', '-baked_at').distinct('bakery__id')
        # 'recent_post': Post.objects.filter(date_posted="date_posted").order_by("-created_at")[:1],
        'recent_video': Video.objects.all()[0]
    }
    return render(request, 'home/home.html', context)


def about(request):
    return render(request, 'home/about.html')


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        content = request.POST['content']
        print(name, email, phone, content)

        if len(name) < 2 or len(email) < 3 or len(phone) < 10 or len(content) < 4:
            messages.error(request, "Please fill the form correctly")
        else:
            contact = Contact(name=name, email=email, phone=phone, content=content)
            contact.save()
            messages.success(request, "Your message has been successfully sent")

    return render(request, 'home/contact.html')


def search(request):
    query = request.GET['query']
    if len(query) > 78:
        allPosts = Post.objects.none()
    else:
        allPostsTitle = Post.objects.filter(title__icontains=query)
        allPostsContent = Post.objects.filter(content__icontains=query)
        allPosts = allPostsTitle.union(allPostsContent)

    if allPosts.count() == 0:
        messages.warning(request, "No search results found. Please refine your query")
    params = {'allPosts': allPosts, 'query': query}
    return render(request, 'home/search.html', params)


def handleSignup(request):
    if request.method == 'POST':
        # Get the post parameters
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        # Check for errorneous inputs
        # username should be under 10 characters
        if len(username) > 10:
            messages.error(request, "Username must be under 10 characters")
            return redirect('home:home')

        # username should be alphanumeric
        if not username.isalnum():
            messages.error(request, "Username should only contain letters and numbers")
            return redirect('home:home')

        # passwords should match
        if pass1 != pass2:
            messages.error(request, "Passwords do not match")
            return redirect('home:home')

        # Create the user
        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname
        myuser.save()
        messages.success(request, "Your DjangoApp account has been successfully created")
        return redirect('home:home')
    else:
        return HttpResponse('404 - Not Found')


def handleLogin(request):
    if request.method == 'POST':
        # Get the post parameters
        loginusername = request.POST['loginusername']
        loginpassword = request.POST['loginpassword']

        user = authenticate(username=loginusername, password=loginpassword)

        if user is not None:
            login(request, user)
            messages.success(request, "Successfully Logged In")
            return redirect('home:home')
        else:
            messages.error(request, "Invalid Credentials, Please try again")
            return redirect('home:home')

    return HttpResponse('my 404 - Not Found')


def handleLogout(request):
    logout(request)
    messages.success(request, "Successfully Logged Out")
    return redirect('home:home')

templates/home/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock title %}

{% block aboutactive %} active {% endblock aboutactive %}


{% block content %}


<section class="header1 cid-qyvisAZ1Bw" id="header1-7" data-rv-view="758">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="mbr-white col-md-10">
                <h1 class="mbr-section-title align-center mbr-bold pb-3 mbr-fonts-style display-5">Responsive Bootstrap About Us Page Template</h1>
                <h6 class="mbr-section-subtitle align-center mbr-light pb-3 mbr-fonts-style display-2">MEET OUR TEAM</h6>
                <p class="mbr-text align-center pb-3 mbr-fonts-style display-5">
                    We are all very different. We were born in different cities, at different times, we love different music, food, movies. But we have something that unites us all. It is our company. We are its heart. We are not just a team, we are a family.
                </p>
                <div class="mbr-section-btn">
                    <a class="btn btn-md btn-black-outline display-4" href="index.html#form1-4">
                        <button class="btn btn-success">CONTACT US</button></a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="features1 cid-qyvcAqZyNq" id="features1-1" data-rv-view="764">
    <div class="container-md-4 ">
        <div class="media-container-row">
            <div class="card about-card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-img pb-3">
                    <span class="mbr-iconfont mbri-users" style="color: rgb(0, 0, 0);" media-simple="true"></span>
                </div>
                <div class="card-box">
                    <h4 class="card-title py-3 mbr-fonts-style display-5">
                        Creativity</h4>
                    <p class="mbr-text mbr-fonts-style display-7">
                        It's the ability to think outside the box. We make decisions, create something new and generate a lot of ideas.
                    </p>
                </div>
            </div>

            <div class="card about-card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-img pb-3">
                    <span class="mbr-iconfont mbri-globe" style="color: rgb(0, 0, 0);" media-simple="true"></span>
                </div>
                <div class="card-box">
                    <h4 class="card-title py-3 mbr-fonts-style display-5">
                        Worldwide</h4>
                    <p class="mbr-text mbr-fonts-style display-7">
                        All sites you make with Mobirise are mobile-friendly. You don't have to create a special mobile version of your site.
                    </p>
                </div>
            </div>

            <div class="card about-card p-3 col-12 col-md-6 col-lg-4">
                <div class="card-img pb-3">
                    <span class="mbr-iconfont mbri-smile-face" style="color: rgb(0, 0, 0);" media-simple="true"></span>
                </div>
                <div class="card-box">
                    <h4 class="card-title py-3 mbr-fonts-style display-5">
                        Unique Styles
                    </h4>
                    <p class="mbr-text mbr-fonts-style display-7">
                        Mobirise offers many site blocks in several themes, and though these blocks are pre-made, they are flexible.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mbr-section form1 cid-qyvf9K0GGo" id="form1-4" data-rv-view="791">
    <div class="container">
        <div class="row justify-content-center">
            <div class="title col-12 col-lg-8">
                <h5 class="mbr-section-title align-center pb-3 mbr-fonts-style display-4">
                    CONTACT US</h5>

            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="media-container-column col-lg-8" data-form-type="formoid">
                <div data-form-alert="" hidden="">
                    Thanks for filling out the form!
                </div>
                <form class="mbr-form" action="https://mobirise.com/" method="post" data-form-title="Mobirise Form"><input type="hidden" data-form-email="true" value="R46ImfT8lRYLhZq6vpVE63L0V35bOdmwHjgn18Tp/HdDujD3JfWe/8bm7YjE2vjZZ7JFQMRNRIinYQUh3aNa2qi1GshxArFhHAffNuiFsZiNLfMCF8KElmS7V7lbqBIL">
                    <div class="row row-sm-offset">
                        <div class="col-md-4 multi-horizontal" data-for="name">
                            <div class="form-group">
                                <label class="form-control-label mbr-fonts-style display-7" for="name-form1-4">Name</label>
                                <input type="text" class="form-control-contact" name="name" data-form-field="Name" required="" id="name-form1-4">
                            </div>
                        </div>
                        <div class="col-md-4 multi-horizontal" data-for="email">
                            <div class="form-group">
                                <label class="form-control-label mbr-fonts-style display-7" for="email-form1-4">Email</label>
                                <input type="email" class="form-control-contact" name="email" data-form-field="Email" required="" id="email-form1-4">
                            </div>
                        </div>
                        <div class="col-md-4 multi-horizontal" data-for="phone">
                            <div class="form-group">
                                <label class="form-control-label mbr-fonts-style display-7" for="phone-form1-4">Phone</label>
                                <input type="tel" class="form-control-contact" name="phone" data-form-field="Phone" id="phone-form1-4">
                            </div>
                        </div>
                    </div>
                    <div class="form-group" data-for="message">
                        <label class="form-control-label mbr-fonts-style display-7" for="message-form1-4">Message</label>
                        <textarea type="text" class="form-control-contact" name="message" rows="7" data-form-field="Message" id="message-form1-4"></textarea>
                    </div>
                    <span class="input-group-btn"><button href="" type="submit" class="btn btn-form btn-black-outline display-4">SEND FORM</button></span>
                </form>
            </div>
        </div>
    </div>
</section>

<section once="" class="cid-qyvfbdUvMJ" id="footer6-5" data-rv-view="794">
    <div class="container">
        <div class="media-container-row align-center mbr-white">
            <div class="col-12">
                <p class="mbr-text mb-0 mbr-fonts-style display-7">
                    © Copyright 2018 <a href="https://mobirise.com/bootstrap-template/" class="text-black">Free Bootstrap Templates</a> - All Rights Reserved
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/home/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Home {% endblock title %}
{% block contactactive %} active {% endblock contactactive %}
{% block content %}
<div class="container my-3">
<h3>Contact iCoder Admin</h3>
<form method="post" action="/contact">
{% csrf_token %}
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name" aria-describedby="name"> 
  </div>
  <div class="form-group">
    <label for="email">Email address</label>
    <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="phone">Phone Number</label>
    <input type="phone" class="form-control" name="phone" id="phone">
  </div>
  <div class="form-group">
    <label for="content">Describe your issue:</label> 
    <textarea class="form-control" name="content" id="content" cols="30" rows="5"></textarea>
  </div>
   
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</div>
{% endblock content %}

templates/home/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock title %}
{% block homeactive %} active {% endblock homeactive %}

{% block content %}
<div class="container my-3">
    <div class="jumbotron">
        <h1 class="display-4">Welcome to Django App!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to
            featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="/blog" role="button">Go to Blog</a>
	      <a class="btn btn-primary btn-lg" href="/videoportal" role="button">Go to videoportal</a>
    </div>
</div>

<div class="container">
	<h2>Recent Activities</h2>
	<div class="col">
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      <div class="col-8 p-4">
        <a class="d-inline-block mb-2 href=" {% url 'blog:post-detail' recent_post.id %} ">
          <h3>{{ recent_post.title }}</h3>
            </a>
            <div class="mb-1 text-muted ">{{ recent_post.date_posted|date:"F d, Y " }}</div>
            <p class="card-text mb-auto ">{{ recent_post.content | truncatechars:200 }}</p>
        <a href=" {% url 'blog:post-detail' recent_post.id %} " class="stretched-link ">Continue reading</a>
      </div>
      <div class="col-4 d-none d-lg-block ">
       <a href="{% url 'blog:post-detail' recent_post.id %} ">
        <img class="imgthumbnail p-3 " width="200 " ; height="250 " ; src="{{ recent_post.blog_logo.url }} ">
      </a>
      </div>
    </div>
  </div>

	<div class="col-12">
    <div class="card p-3 col-3 jumbotron ">
      <div class="card-wrapper">
        <div class="card-img">
          <a href="{% url 'videoportal:video-detail' recent_video.id %}">
            <img class="card-img-thumbnail" src="{{ recent_video.thumbnail.url }}"
             alt={{ recent_videos.title }} title="" media-simple="true"></a>
        </div>
        <div class="card-box">
          <h6 class="card-title pb-3 mbr-fonts-style display-7">
            <a href="{% url 'videoportal:video-detail' recent_video.id %}" class="text-black">{{ recent_video.title }}</a>
          </h6>
          <ul class="list-group list-group-flush">
            <li class="list-group-item-light">{{ recent_video.subtitle1 }}</li>
            <li class="list-group-item-light">{{ recent_video.subtitle2 }}</li>
          </ul>
          <p class="card-text list-group-item-light"><small class="text-muted">{{ recent_video.datetime }} </small></p>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock content %}

templates/home/search.html
{% extends 'base.html' %}

{% block title %} Search Results {% endblock title %}

{% block blogactive %} active {% endblock blogactive %}

{% block content %}
    <div class="container my-3">
        <h2>Search results:</h2>
        {% if allPosts|length < 1 %}
            <p>No search results</p>

            Your search query: <b>{{query}} </b> did not match any documents. <br>
            Suggestions:
            <ul>
            <li>Make sure that all words are spelled correctly.</li>
            <li>Try different keywords.</li>
            <li>Try more general keywords.</li>
            <li>Try fewer keywords.</li>
            </ul>
        {% endif %}
        {% for post in allPosts %}
            <div class="col">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col-8 p-4">
                        <a class="d-inline-block mb-2 href=" {% url 'blog:post-detail' post.id %} ">
                            <h3>{{ post.title }}</h3>
                            </a>
                            <div class="mb-1 text-muted ">{{ post.date_posted|date:"F d, Y " }}</div>
                            <p class="card-text mb-auto ">{{ post.content | truncatechars:200 }}</p>
                        <a href=" {% url 'blog:post-detail' post.id %} " class="stretched-link ">Continue reading</a>
                    </div>
                    <div class="col-4 d-none d-lg-block ">
                    <a href="{% url 'blog:post-detail' post.id %} ">
                        <img class="imgthumbnail p-3 " width="200 " ; height="250 " ; src="{{ post.blog_logo.url }} ">
                    </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}