blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('videoportal/', include(('videoportal.urls', 'videoportal'), namespace='videoportal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
   path('', views.home, name='home'),
   path('about/', views.about, name='about'),
   path('contact/', views.contact, name='contact'),
   path('search/', views.search, name='search'),
   path('signup/', views.handleSignup, name='handleSignup'),
   path('login/', views.handleLogin, name='handleLogin'),
   path('logout/', views.handleLogout, name='handleLogout'),
]

videoportal/urls.py
from django.urls import path

from videoportal.views import (VideoListView, VideoDetailView, VideoFileView)

urlpatterns = [
    path('', VideoListView.as_view(), name='video-home'),
    path('video/<int:id>/', VideoDetailView.as_view(), name='video-detail'),
    path('get_video/<file_name>/', VideoFileView.as_view(), name='video-view'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- custom CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
	      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="shortcut icon " type="image/ico " href="{% static 'media/favicon1.ico' %} ">
	<!-- facebook embed CSS -->
	<script async defer crossorigin="anonymous " src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0 ">
	</script>
	{#	<script src="{% static 'blog/script.js' %}"></script>#}

	<title>{% block title %} {% endblock title %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top py-1">
    <div class="container-fluid">
      <div class="col-md-1 p-3 hide_in_mobile "></div>
      <div class="col-md-8">
        <div class="row">
	        <a class="navbar-brand mr-4" href="{% url 'home:home' %}">Django App</a>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                <li class="nav-item {% block BlogPortalactive %} {% endblock BlogPortalactive %}">
                <a class="nav-link" href="{% url 'blog:blog-home' %}">BlogPortal</a>
              </li>
                <li class="nav-item {% block videoportalactive %} {% endblock videoportalactive %}">
                <a class="nav-link" href="{% url 'videoportal:video-home' %}">VideoPortal</a>
              </li>
                <li class="nav-item {% block aboutactive %} {% endblock aboutactive %}">
                <a class="nav-link" href="{% url 'home:about' %}">About</a>
              </li>
              <li class="nav-item {% block contactactive %} {% endblock contactactive %}">
                <a class="nav-link" href="{% url 'home:contact' %}">Contact</a>
              </li>
            </div>
            <div class="form-inline py-2  ">
              <form method="get" action="{% url 'home:search' %}" class="mr-4" style="display: flex;">
              <input class="form-control mr-sm-2 SearchBar" type="search " placeholder="Search"
                       aria-label="Search" name="query" id="query" style="height: 2rem;">
                <button class="btn btn-sm btn-outline-success" type="submit ">Search</button>
              </form>
            </div>

            {% if user.is_authenticated %}
				      <ul class="navbar-nav mr-2">
				      <li class="nav-item dropdown">
				        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				          Welcome {{request.user}}
				        </a>
				        <div class="dropdown-menu py-0" style="background-color: transparent;border: none;"
				             aria-labelledby="navbarDropdown">
				          <a class="dropdown-item" style="background-color: red;font-weight: bold;color: white;text-align:
				          center;border-radius: 50px;" href="/logout">Logout</a>
				        </div>
				      </li>
				      </ul>
				    {% else %}
				      <!-- Button to trigger Login modal -->
				      <button type="button" class="btn btn-sm btn-success mr-2" data-toggle="modal" data-target="#loginModal"
				        style="height: 2rem;vertical-align: middle;">
				        Login
				      </button>
				      <!-- Button to trigger SignUp modal -->
				      <button type="button" class="btn btn-sm btn-success mr-2" data-toggle="modal" data-target="#signupModal"
				        style="height: 2rem;vertical-align: middle;">
				        SignUp
				      </button>
				    {% endif %}
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                  aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation" style="margin-left: auto;">
            <span class="navbar-toggler-icon"></span>
          </button>
      </div>
      </div>
      <div class="col-md-3 p-3 hide_in_mobile"></div>
    </div>
  </nav>

  <div class="container-fluid mt-5">
      <div class="row">
          <div class="col-12 ">
              {% if messages %}
                {% for message in messages %}
	                <div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show" role="alert">
	                    <strong>Message: </strong> {{ message }}
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
		            </div>
                  {% endfor %}
              {% endif %}
          </div>
          {% block content %} {% endblock %}
      </div>
  </div>

<!-- SignUp Modal -->
	<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="signupModal" aria-hidden="true">
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
	    <div class="modal-header">
	      <h5 class="modal-title" id="signupModalTitle">SignUp Here</h5>
	      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	        <span aria-hidden="true">&times;</span>
	      </button>
	    </div>
	    <div class="modal-body">
	      <form action='signup/' method='post'>
	        <div class="form-group">
	          <label for="username">Username</label>
	          <input type="text" class="form-control" id="username" name="username" placeholder="Choose a unique username (Lowercase & alphanumeric)" required>
	        </div>
	        <div class="form-group">
	          <label for="fname">First Name</label>
	          <input type="text" class="form-control" id="fname" name="fname" placeholder="First Name" required>
	        </div>
	        <div class="form-group">
	          <label for="lname">Last Name</label>
	          <input type="text" class="form-control" id="lname" name="lname" placeholder="Last Name" required>
	        </div>
	        <div class="form-group">
	          <label for="email">Email address*</label>
	          <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com" required>
	        </div>

	        <div class="form-group">
	          <label for="pass1">Choose a Password</label>
	          <input type="password" class="form-control" id="pass1" name="pass1" placeholder="Choose your password" required>
	        </div>
	        <div class="form-group">
	          <label for="pass2">Confirm Password</label>
	          <input type="password" class="form-control" id="pass2" name="pass2" placeholder="Enter your password again" required>
	        </div>

	      {% csrf_token %}
	      <button type="submit" class="btn btn-primary">Submit</button>
	      </form>
	    </div>
	    <div class="modal-footer">
	    </div>
	  </div>
	</div>
	</div>

	<!-- Login Modal -->
	<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
	    <div class="modal-header">
	      <h5 class="modal-title" id="loginModalTitle">Login Here</h5>
	      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	        <span aria-hidden="true">&times;</span>
	      </button>
	    </div>
	    <div class="modal-body">
	      <form action='login/' method='post'>
	        {% csrf_token %}
	        <div class="form-group">
	          <label for="username">Username</label>
	          <input type="text" class="form-control" id="loginusername" name="loginusername"
	                 placeholder="Choose a unique username" required>
	        </div>
	        <div class="form-group">
	          <label for="pass">Password</label>
	          <input type="password" class="form-control" id="loginpassword" name="loginpassword"
	                 placeholder="Enter your password" required>
	        </div>
	        <button type="submit" class="btn btn-primary">Submit</button>
	      </form>
	    </div>
		  <div class="modal-footer">
	    </div>
	  </div>
	</div>
	</div>

	<div class="myScripts">
	  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
	          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
	  </script>
	  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0">
	  </script>
	  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
	          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
	  </script>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
	          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
	  </script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
	          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
	  </script>
	  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0">
	  </script>
	</div>
</body>

</html>